[project]
name = "allan_variance_analyzer_workspace"
version = "0.0.0"  # Not used
requires-python = ">= 3.10"
dependencies = [
  "allan-variance-analyzer",
  "allan-variance-analyzer-ros",
]

[tool.uv]
package = false # https://docs.astral.sh/uv/reference/settings/#package
required-version = ">=0.6.0"

[tool.uv.sources]
allan-variance-analyzer = { workspace = true}
allan-variance-analyzer-ros = { workspace = true }

[tool.uv.workspace]
members = ["allan-variance-analyzer", "allan-variance-analyzer-ros"]

[tool.pytest.ini_options]
consider_namespace_packages = true
pythonpath = [
    "allan-variance-analyzer/src",
    "allan-variance-analyzer-ros/src"
]
