[project]
name = "allan_variance"
version = "1.0.0"
description = "Tools for Allan Variance Analysis"
authors = [{ name = "Varun Agrawal", email = "varunagrawal@gatech.edu" }]
readme = "README.md"
license = { text = "BSD 3-Clause License" }
keywords = ['Research', 'Inertial', 'Allan Variance']

requires-python = ">= 3.10"

dependencies = [
  "numpy>=2.2.4",
  "jax>=0.4.38",
  "pyaml>=21.10.1",
  "attrdict>=2.0.1",
  "tqdm>=4.62.2",
  "loguru>=0.6.0",
  "rosbags>=0.10.4",
  "matplotlib>=3.10.7",
]

[project.urls]
repository = "https://github.com/varunagrawal/allan_variance"
homepage = "https://github.com/varunagrawal/allan_variance"

[project.optional-dependencies]
dev = ["pytest>=7.1.1", "pylint>=2.13.2"]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["allan_variance"]
exclude = ["config", "ros", "ros2", "simulator"]
namespaces = false

[tool.setuptools.package-data]
roboplot = ["py.typed", "*.pyi", "**/*.pyi"]

[tool.mypy]
ignore_missing_imports = true
