[project]
name = "allan_variance_analyzer"
version = "1.0.1"
description = "Efficient Tool for Allan Variance Analysis"
authors = [{ name = "Varun Agrawal", email = "varagrawal@gmail.com" }]
readme = "README.md"
license = { text = "BSD 3-Clause License" }
keywords = ['Research', 'Inertial', 'Allan Variance']

requires-python = ">= 3.10"

dependencies = [
  "numpy>=2.2.4",
  "scipy>=1.18.0",
  "pyaml>=21.10.1",
  "attrdict>=2.0.1",
  "tqdm>=4.62.2",
  "loguru>=0.6.0",
  "matplotlib>=3.10.7",
]

[project.urls]
repository = "https://github.com/varunagrawal/allan_variance"
homepage = "https://github.com/varunagrawal/allan_variance"

[project.optional-dependencies]
dev = ["pytest>=7.1.1", "pylint>=2.13.2"]

[build-system]
requires = ["uv_build >= 0.11.23, <0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "."
module-name = "allan_variance_analyzer"
source-exclude = ["config", "ros", "ros2", "simulator"]

namespaces = false
