[project]
name = "allan_variance_analyzer_ros"
version = "1.0.0"
description = "Allan Variance Analysis with ROS Bag Support"
authors = [{ name = "Varun Agrawal", email = "varagrawal@gmail.com" }]
readme = "README.md"
license = { text = "BSD 3-Clause License" }
keywords = ['Research', 'Inertial', 'Allan Variance']

requires-python = ">= 3.10"

dependencies = [
  "allan_variance_analyzer>=1.0.4",
  "rosbags>=0.9.0",
]

[project.urls]
repository = "https://github.com/varunagrawal/allan_variance"
homepage = "https://github.com/varunagrawal/allan_variance"

[project.optional-dependencies]
dev = ["pytest>=7.1.1", "pylint>=2.13.2"]

[build-system]
requires = ["uv_build >= 0.11.23, <0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "allan_variance_analyzer.ros"
namespace = true

[tool.uv.sources]
allan-variance-analyzer = { workspace = true }

[tool.pytest.ini_options]
pythonpath = ["src"]
